@startuml DiagrammaSequenzaEliminazioneMessaggio

actor Utente
participant Messaggio
participant SnackBar
participant Console
participant BannerEliminazione
participant RuoloChat
participant ChatService
database DatabaseMessaggi

Utente->Messaggio: PremeMessaggio
Messaggio->RuoloChat: MessaggioPremuto(messaggio)

alt Ruolo chat è Scrittore

    RuoloChat->RuoloChat: Controllo proprietà del messaggio

    opt Messaggio inviato dall'Utente che ha premuto

        RuoloChat->RuoloChat: Controlla timestamp invio

        alt Messaggio inviato meno di 30s fa 
            RuoloChat->BannerEliminazione: Chiedi se eliminare il messaggio 
            BannerEliminazione->Utente: Richiedi se eliminare

            Utente->BannerEliminazione: RispostaEliminazione
            BannerEliminazione->RuoloChat: inviaRisposta

            opt Elimina
                RuoloChat->ChatService: EliminaMessaggio(messaggio)

                ChatService->DatabaseMessaggi: Chiedi riferimento alla Chat

                ChatService->DatabaseMessaggi: Chiedi gli ultimi 2 messaggi inviati in chat

                opt Messaggio da elimiare è l'ultimo della chat

                    alt esiste un penultimo messaggio
                        ChatService->ChatService: imposta come ultimo messaggio il penultimo
                        ChatService->DatabaseMessaggi: imposta ultimo messaggio chat il penultimo
                    else 
                        ChatService->DatabaseMessaggi: imposta come utimo messaggio Nuova Chat 
                    end
                end

            
    
                ChatService->DatabaseMessaggi: Elimina il messaggio

                RuoloChat->SnackBar: Manda Risposta Eliminazione

                SnackBar->Utente: Avvisa Eliminazione effettuata

                break errore eliminazione
                    ChatService->Console: StampaErrore
                    Console->Console: MostraErrore
                end
            end

        else
            RuoloChat->SnackBar: avvisa impossibile eliminare per tempo scad
            SnackBar->Utente: mostra impossibilità eliminazione per tempo scaduto

        end
        
    end 
else
    RuoloChat->SnackBar: Avvisa Non si possono eliminare messaggi
    SnackBar->Utente: Avvisa solo modalità lettura

end



@enduml