// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqH4leYfwH7x7eROsk_Gbd6uI0eehG8rQ',
    appId: '1:669955089150:web:0c20668b9f717faa3e7baf',
    messagingSenderId: '669955089150',
    projectId: 'caa-application-1aaac',
    authDomain: 'caa-application-1aaac.firebaseapp.com',
    storageBucket: 'caa-application-1aaac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8fz-sbi5mrpY2D-7cLkiZp3MrtIFLdk4',
    appId: '1:669955089150:android:fa056348149c59673e7baf',
    messagingSenderId: '669955089150',
    projectId: 'caa-application-1aaac',
    storageBucket: 'caa-application-1aaac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzwG1WG6il0BS_pH4GkVPDvs0ob8uiVs8',
    appId: '1:669955089150:ios:b1499a28a374235a3e7baf',
    messagingSenderId: '669955089150',
    projectId: 'caa-application-1aaac',
    storageBucket: 'caa-application-1aaac.firebasestorage.app',
    iosBundleId: 'com.example.chatbypics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzwG1WG6il0BS_pH4GkVPDvs0ob8uiVs8',
    appId: '1:669955089150:ios:b1499a28a374235a3e7baf',
    messagingSenderId: '669955089150',
    projectId: 'caa-application-1aaac',
    storageBucket: 'caa-application-1aaac.firebasestorage.app',
    iosBundleId: 'com.example.chatbypics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqH4leYfwH7x7eROsk_Gbd6uI0eehG8rQ',
    appId: '1:669955089150:web:0c20668b9f717faa3e7baf',
    messagingSenderId: '669955089150',
    projectId: 'caa-application-1aaac',
    authDomain: 'caa-application-1aaac.firebaseapp.com',
    storageBucket: 'caa-application-1aaac.firebasestorage.app',
  );
}
