@startuml  DiagrammaAttivitaEliminaizoneMessaggio

start
    :utente preme messaggio <evento>; <<acceptEvent>>
    :invia dati messaggio a Ruolo <invio>; <<sendSignal>>
    :Ruolo riceve messaggi <ricevi>; <<acceptEvent>>
    if(utente è nella chat con permessi di scrittura?) then (yes)
        if(messaggio è dell'utente?) then (yes)
            if(messaggio mandato meno di 30s fa?) then(yes)
                :chiedi se vuole eliminare il messaggio <invio>; <<acceptEvent>>
                
                :aspetta risposta utente <timeEvent>; <<timeEvent>>

                if(vuole eliminare?) then (yes)

                    :richiedi ultimi 2 messaggi chat <invio>; <<sendSignal>>
                    :attendi arrivo messaggi <timeEvent>; <<timeEvent>>


                    if(il messaggio è l'ultimo della chat?) then(yes)
                        if(esiste un penultimo messaggio?) then(yes)
                            :imposta penultimo messaggio come ultimo della chat;
                        else(no)
                            :imposta "Nuova chat" come ultimo messaggio della chat;
                        endif

                        :invia ultimo messaggio a DB <invio>; <<sendSignal>>

                    else (no) 
                    endif

                    :invia richiesta elimina messaggio a db <invio>; <<sendSignal>>
                    :attendi Eliminazione messaggio <timeEvent>; <<timeEvent>>

                    if(errore?) then(no)
                        :comunica eliminazione messaggio a utente <invio>; <<sendSignal>>
                    else(yes)
                        :mostra errore in console <invio>; <<sendSignal>>
                        stop
                    endif
                    

            else (no)
            endif

            else(no)
                :avvisa Utente impossibile eliminare, tempo scaduto <invio>; <<sendSignal>>
            endif
            

            else(no)
                
        endif

    else(no)
        :avvisa Utente solo lettura <invio>; <<sendSignal>>
    endif
stop

@enduml