@startuml DiagrammaAttivitaGestioneSuggerimentiPittogrammi
start
:apri file json;
:copia in memoria i suggerimenti letti nel file <invio>; <<sendSignal>>
:chiudi file json;
repeat
repeat
:attendi nuovo pittogramma inserito(time event); <<timeEvent>>
repeat while(esisteva un pittogramma inserito precedentemente al nuovo?) is (no) not (yes)
    :prendi id pittogramma precedente;
    :prendi URL pittogramma nuovo;
    :cerca in memoria i suggerimenti per id pittogramma precedente;
if(esiste una lista di suggerimenti per il vecchio id?) then (yes)
    :salva lista dei suggerimenti;
else(no)
    :crea lista vuota suggerimenti per il vecchio id;
endif
if(esiste nella lista suggerimenti salvata l'URL nuovo) then(yes)
    :rimuovi l'URL nuovo dalla lista;
else (no)
endif 
:inserisci il nuovo URL in testa alla lista suggerimenti;

if(lista suggerimenti>3 elementi?) then (yes)
    :rimuovi ultimo elemento della lista;
else (no)
endif
:aggiorna la struttura in memoria;
:apri file Json;
:scrivi sul file Json le modifiche <invio>; <<sendSignal>>
:chiudi file Json;

@enduml